name: Node.js Backend CI

#1 Trigger: run on every code push to the main branch
on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    # 1. Inject the secrets as environment variables into the VM
    env:
      PORT: ${{ secrets.PORT }}
      INTERNAL_API_KEY: ${{ secrets.INTERNAL_API_KEY }}
      MONGO_URI: ${{ secrets.MONGO_URI }}
      MONGO_DB_NAME: ${{ secrets.MONGO_DB_NAME }}
      JWT_SECRET: ${{ secrets.JWT_SECRET }}
      JWT_EXPIRES_IN: ${{ secrets.JWT_EXPIRES_IN }}

    steps:
    - name: Checkout repository code
      uses: actions/checkout@v4

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20.x' 

    - name: Install dependencies
      run: npm install

    - name: Run tests
      run: npm test
